spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true