spring:
  application:
    name: eureka-server
  config:
    # config 서버 추가
    import: optional:configserver:http://localhost:8071
  cloud:
    # ribbon 로드 밸런서를 비활성화
    loadbalancer:
      ribbon:
        enabled: false