#version: '3.7'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command:
      - start-dev