spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  # ?? ??? configserver ?? ?? ??
  config:
    import: optional:configserver:http://localhost:8071

#management:
#  endpoints:
#    web:
#      base-path: /


