spring:
  application:
    name: licensing-service
  config:
    import: optional:configserver:http://localhost:8071

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  instances:
    licenseService:
      # actuator에 상태를 등록함
      registerHealthIndicator: true
      # 최근 10개 단위로 성공률 측정
      slidingWindowSize: 10
      # 최소5개가 넘어가면 성공률 측정
      minimumNumberOfCalls: 5
      # HALF-OPEN 상태에서 CLOSED/OPEN 상태로 가기 위한 개수
      # 예) 임계치50%, 3회 호출에서 1회 실패면 CLOSED로 넘어감, 2회 실패면 OPEN으로 넘어감
      permittedNumberOfCallsInHalfOpenState: 3
      # 별도의 트리거 없이 OPEN에서 HALF-OPEN으로 넘어감
      automaticTransitionFromOpenToHalfOpenEnabled: true
      # OPEN 상태에서의 대기시간
      waitDurationInOpenState: 5s
      # 실패 임계치
      failureRateThreshold: 50
      # 서킷 브레이커 이벤트 버퍼 사이즈
      # /actuator/circuitbreakerevents 경로를 통해 확인 가능
      eventConsumerBufferSize: 10
      # 오류로 처리할 예외 클래스 목록
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException

#management:
#  endpoints:
#    web:
#      base-path: /


