#version: '3.7'
services:
  database:
    image: postgres:latest
    container_name: database
    hostname: database
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "ostock_dev"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 5s
      start_interval: 5s
      interval: 5s
      timeout: 3s
      retries: 3
  configserver:
    image: ostock/config-server:latest
    container_name: configserver
    hostname: configserver
    ports:
      - "8071:8071"
    networks:
      - backend
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://configserver:8071/actuator/health | grep UP || exit 1"]
        start_period: 5s
        start_interval: 5s
        interval: 5s
        timeout: 3s
        retries: 10
  eurekaserver:
    image: ostock/eureka-server:latest
    container_name: eurekaserver
    hostname: eurekaserver
    ports:
      - "8070:8070"
    environment:
      - "SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8071"
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://eurekaserver:8070/actuator/health | grep UP || exit 1" ]
      start_period: 5s
      start_interval: 5s
      interval: 5s
      timeout: 3s
      retries: 10
  licensingservice:
    image: ostock/licensing-service:latest
    container_name: licensingservice
    hostname: licensingservice
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8071"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8180:8180"
    networks:
      - backend
  organizationservice:
    image: ostock/organization-service:latest
    container_name: organizationservice
    hostname: organizationservice
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CONFIG_IMPORT=optional:configserver:http://configserver:8071"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
    driver: bridge