# bootstrap.yml -> application.yml로 변경됨
# https://newbedev.com/bootstrap-yml-configuration-not-processed-anymore-with-spring-cloud-2020-0
spring:
  application:
    name: config-server
  # 백엔드 저장소(파일 시스템)와 관련된 스프링 프로파일을 설정한다.
  profiles:
#    active: native
    # active: native, git
     active: git
  cloud:
    config:
      server:
#        # 로컬 구성 정보: classpath 위치나 파일 시스템의 위치가 될 수 있다.
#        native:
#          # 특정 파일 시스템 폴더에서 읽어 온다.
#          search-locations: classpath:/config
#        git:
#          uri: https://github.com/kdkcom1234/spring-cloud-config
          git:
            uri: https://github.com/kdkcom1234/spring-mircroservice-in-action
            searchPaths: config
server:
  port: 8071